### Importing packages

In [1]:
import numpy as np
import matplotlib.pyplot as plt

### Loading the data

In [2]:
data=np.loadtxt('Audiobooks_data.csv',delimiter=',')

In [3]:
inputs=data[:,:-1]
target=data[:,-1:]

### balancing the data

In [4]:
target_sum=int(np.sum(target))
zero_sum=0
indices_to_remove=[]
for i in range(target.shape[0]):
    if target[i]==0:
        zero_sum +=1
        if zero_sum>target_sum:
            indices_to_remove.append(i)


In [5]:
balanced_target=np.delete(target,indices_to_remove,axis=0)
balanced_input=np.delete(inputs,indices_to_remove,axis=0)

### Scaling the data

In [6]:
from sklearn import preprocessing

In [7]:
scaled_input=preprocessing.scale(balanced_input)

### Shuffling the data

In [8]:
shuffle_data=np.arange(scaled_input.shape[0])
np.random.shuffle(shuffle_data)

shuffle_target=balanced_target[shuffle_data]
shuffle_input=balanced_input[shuffle_data]

### Batching the data

In [9]:
def batch_data(inputs,targets,per1,per2):
    import numpy as np
    global train_input
    global train_target
    global valid_input
    global valid_target
    global test_input
    global test_target
    count=inputs.shape[0]
    train_count=int(per1*count)
    valid_count=int(per2*count)
    test_count=count-train_count-valid_count
    train_input=inputs[:train_count]
    train_target=targets[:train_count]
    valid_input=inputs[train_count:train_count+valid_count]
    valid_target=targets[train_count:train_count+valid_count]
    test_input=inputs[train_count+valid_count:]
    test_target=targets[train_count+valid_count:]
    return train_input,train_target,valid_input,valid_target,test_input,test_target
   
   
    

In [10]:
batch_data(shuffle_input,shuffle_target,0.75,0.15)

(array([[1.2122e+04, 2.1600e+03, 2.1600e+03, ..., 4.7520e+02, 0.0000e+00,
         2.4000e+01],
        [1.8250e+04, 2.1600e+03, 2.1600e+03, ..., 6.2316e+02, 0.0000e+00,
         4.7000e+01],
        [1.9477e+04, 2.1600e+03, 2.1600e+03, ..., 5.1840e+02, 0.0000e+00,
         0.0000e+00],
        ...,
        [2.4202e+04, 1.0800e+03, 1.0800e+03, ..., 0.0000e+00, 0.0000e+00,
         8.0000e+00],
        [2.5501e+04, 1.1880e+03, 1.1880e+03, ..., 7.3656e+02, 0.0000e+00,
         0.0000e+00],
        [3.2950e+03, 1.6200e+03, 1.6200e+03, ..., 6.8040e+02, 0.0000e+00,
         5.5000e+01]]),
 array([[0.],
        [0.],
        [0.],
        ...,
        [1.],
        [0.],
        [0.]]),
 array([[1.0097e+04, 2.1600e+03, 2.1600e+03, ..., 6.8040e+02, 0.0000e+00,
         0.0000e+00],
        [2.3272e+04, 2.1600e+03, 2.1600e+03, ..., 0.0000e+00, 0.0000e+00,
         2.0600e+02],
        [1.8418e+04, 1.6200e+03, 1.6200e+03, ..., 5.1084e+02, 0.0000e+00,
         0.0000e+00],
        ...,
        [

In [11]:
train_input

array([[1.2122e+04, 2.1600e+03, 2.1600e+03, ..., 4.7520e+02, 0.0000e+00,
        2.4000e+01],
       [1.8250e+04, 2.1600e+03, 2.1600e+03, ..., 6.2316e+02, 0.0000e+00,
        4.7000e+01],
       [1.9477e+04, 2.1600e+03, 2.1600e+03, ..., 5.1840e+02, 0.0000e+00,
        0.0000e+00],
       ...,
       [2.4202e+04, 1.0800e+03, 1.0800e+03, ..., 0.0000e+00, 0.0000e+00,
        8.0000e+00],
       [2.5501e+04, 1.1880e+03, 1.1880e+03, ..., 7.3656e+02, 0.0000e+00,
        0.0000e+00],
       [3.2950e+03, 1.6200e+03, 1.6200e+03, ..., 6.8040e+02, 0.0000e+00,
        5.5000e+01]])